# creer un fichier host_list dans chaque container qui , le fichier doit contenir les machines qui ne sont pas du meme groupe que lui 
--- 
- name: "playing with jinja2"
  hosts: all
  become: true 
  vars:
    others_hosts: /home/sshuser/others_hosts
    host_list_file: /home/sshuser/hosts_lists 
    last_item: "{{ groups.all | last }}"
  gather_facts: false
  tasks: 
    - name: "debug"
      ansible.builtin.debug:
        var: groups.all
        
# adresse ip d'une machine hostvars["machine2"].ansible_host 
    - name: "building the host_list file wich contain all ips except thhostvars.e one in the same group"
      ansible.builtin.lineinfile:
        path: host_list_file
        line: | 
          {% for host in groups.all %}
             {% if group_names !=  hostvars[host].group_names %}
                 [{{ host }}]
                 {{ hostvars[host].ansible_host }} {{ hostvars[host].group_names[0] }}
              {% endif %}   
          {% endfor %}
        create: yes

    - name: "Creating file others_hosts"
      ansible.builtin.lineinfile:
        path: others_hosts
        line: |
          {% if last_item == inventory_hostname %}
             {% for host in groups.all %}
                {% if  hostvars[host].ansible_host != ansible_host %}
                   [{{ host }}]
                   {{ hostvars[host].ansible_host }} {{ hostvars[host].group_names[0] }}
                {% endif %}
             {% endfor %}
          {% endif %}
        create: yes
        
    - name: "Creating file server_host"
      ansible.builtin.lineinfile:
        path: /home/sshuser/server_host
        line: | 
          
             {% if last_item != inventory_hostname %}
               [{{ last_item }}]
               {{ hostvars[last_item].ansible_host }} 
             {% endif %}
     
        create: yes      